#!/usr/bin/env python3
# Copyright 2026 Exabeam, Inc.
# SPDX-License-Identifier: Apache-2.0
"""Self-contained smoke tests for the Praxa render pipeline (schema.py + render.py).

No pytest dependency — run directly:

    python3 tests/render/test_render.py

Covers:
  * schema validation accepts a well-formed canonical fixture
  * render.py produces HTML with zero unsubstituted placeholders / leftover markers
  * render.py output is byte-deterministic
  * rendered HTML/TXT match the committed golden files (tests/fixtures/finbot.golden.*)
  * HTML normalises stray HTML entities in prose (no double-escaping)
  * --out-txt-only mode works
  * every committed regression baseline under tests/baselines/ validates against
    schema.py, and the post-relicense ones re-render byte-identically from their
    JSON and quote their remit doc verbatim
  * negative cases (legacy bare list, missing field, count mismatch, bad enum,
    missing RAISE category, broken anchor) all fail loudly with a non-zero exit
"""
from __future__ import annotations

import glob
import json
import os
import re
import subprocess
import sys
import tempfile

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
SKILL_DIR = os.path.join(REPO_ROOT, "skills", "behavior-verifier")
RENDER_PY = os.path.join(SKILL_DIR, "render.py")
TEMPLATE = os.path.join(SKILL_DIR, "report_template.html")
FIXTURE = os.path.join(REPO_ROOT, "tests", "fixtures", "finbot.canonical.json")

sys.path.insert(0, SKILL_DIR)
import schema  # noqa: E402

_passed = 0
_failed = 0


def check(name, cond, detail=""):
    global _passed, _failed
    if cond:
        _passed += 1
        print(f"  ok   {name}")
    else:
        _failed += 1
        print(f"  FAIL {name}" + (f"  — {detail}" if detail else ""))


def run_render(args):
    return subprocess.run([sys.executable, RENDER_PY, *args],
                          capture_output=True, text=True)


def main():
    tmp = tempfile.mkdtemp(prefix="praxa_render_test_")
    data = json.load(open(FIXTURE, encoding="utf-8"))

    # 1. schema accepts the fixture
    try:
        schema.validate(data)
        check("schema.validate accepts the canonical fixture", True)
    except schema.SchemaError as e:
        check("schema.validate accepts the canonical fixture", False, str(e))

    # 2. happy-path render
    out_html = os.path.join(tmp, "a.html")
    out_txt = os.path.join(tmp, "a.txt")
    r = run_render(["--findings", FIXTURE, "--template", TEMPLATE,
                    "--out-html", out_html, "--out-txt", out_txt])
    check("render exits 0 on the fixture", r.returncode == 0, r.stderr.strip())
    html = open(out_html, encoding="utf-8").read() if os.path.exists(out_html) else ""
    txt = open(out_txt, encoding="utf-8").read() if os.path.exists(out_txt) else ""
    check("HTML has no unsubstituted {{PLACEHOLDER}}",
          not re.search(r"\{\{[A-Z0-9_]+\}\}", html))
    check("HTML has no leftover REPEAT/END/PICK/Variant markers",
          not re.search(r"<!--\s*(REPEAT:|END:|PICK:|Variant [AB]:)", html))
    check("HTML strips all template comments (incl. the license header)", "<!--" not in html)
    check("HTML carries no Exabeam copyright / proprietary notice in the report body",
          "Copyright" not in html and "Proprietary" not in html and "All Rights Reserved" not in html)
    check("HTML footer carries the Praxa attribution and project-sponsor link",
          "project sponsor" in html and "exabeam.com" in html and "github.com/Exabeam/deckard" in html)
    check("HTML carries the agent name and version", "FinBot" in html and "Praxa v0.3.0" in html)
    check("TXT footer carries the Praxa attribution and project-sponsor link",
          "Generated by Praxa" in txt and "exabeam.com" in txt and "github.com/Exabeam/deckard" in txt)
    bad_links = [h for h in re.findall(r'href="([^"]*)"', html)
                 if not (h.startswith("#") or h.startswith("http://") or h.startswith("https://"))]
    check("HTML has no relative/broken <a href> (only #anchors and absolute URLs)",
          not bad_links, f"found: {bad_links}")
    check("HTML footer findings tally matches the fixture",
          "8 Critical" in html and "6 High" in html and "2 Medium" in html)
    check("TXT summary is non-empty and names the agent", "FinBot" in txt and len(txt) > 200)
    check("TXT lists Critical findings", "CRITICAL FINDINGS" in txt)

    # 3. determinism
    out_html2 = os.path.join(tmp, "b.html")
    out_txt2 = os.path.join(tmp, "b.txt")
    run_render(["--findings", FIXTURE, "--template", TEMPLATE,
                "--out-html", out_html2, "--out-txt", out_txt2])
    check("HTML render is byte-deterministic",
          open(out_html, "rb").read() == open(out_html2, "rb").read())
    check("TXT render is byte-deterministic",
          open(out_txt, "rb").read() == open(out_txt2, "rb").read())

    # 3b. golden-file fixtures — the rendered HTML/TXT for the canonical fixture
    #     must match what's committed, byte for byte. This is the regression net
    #     for the renderer + template + derived-value tables together: any change
    #     to render.py, report_template.html, or the fixture that alters output
    #     trips this. To intentionally accept new output, regenerate the goldens:
    #       python3 skills/behavior-verifier/render.py \
    #         --findings tests/fixtures/finbot.canonical.json \
    #         --template skills/behavior-verifier/report_template.html \
    #         --out-html tests/fixtures/finbot.golden.html \
    #         --out-txt  tests/fixtures/finbot.golden.txt
    #     ...and review the diff before committing.
    golden_html = os.path.join(REPO_ROOT, "tests", "fixtures", "finbot.golden.html")
    golden_txt = os.path.join(REPO_ROOT, "tests", "fixtures", "finbot.golden.txt")
    check("HTML render matches the committed golden file (byte-identical)",
          os.path.isfile(out_html) and os.path.isfile(golden_html)
          and open(out_html, "rb").read() == open(golden_html, "rb").read(),
          "rendered HTML differs from (or one side is missing) tests/fixtures/finbot.golden.html — see header comment to regenerate")
    check("TXT render matches the committed golden file (byte-identical)",
          os.path.isfile(out_txt) and os.path.isfile(golden_txt)
          and open(out_txt, "rb").read() == open(golden_txt, "rb").read(),
          "rendered TXT differs from (or one side is missing) tests/fixtures/finbot.golden.txt — see header comment to regenerate")

    # 3c. HTML-entity tolerance in prose. The SKILL prompt asks for literal
    #     characters, but the renderer must normalise an entity written by
    #     mistake: un-escape prose before re-escaping for HTML (so &mdash; ->
    #     &mdash; not &amp;mdash;) and decode it entirely for the .txt summary.
    #     (The fixture has no entities, so this runs on a mutated copy.)
    ent = json.loads(json.dumps(data))
    ent["behavior_summary"] = "Tooling <code>a &amp; b</code> &mdash; see &lt;project&gt; notes."
    ent["raise_posture"]["categories"][0]["rationale"] = "Range &lt;1.0.0&gt; &amp; a &mdash; b."
    ent_path = os.path.join(tmp, "ent.json")
    with open(ent_path, "w", encoding="utf-8") as fh:
        json.dump(ent, fh)
    ent_html = os.path.join(tmp, "ent.html")
    ent_txt = os.path.join(tmp, "ent.txt")
    run_render(["--findings", ent_path, "--template", TEMPLATE, "--out-html", ent_html, "--out-txt", ent_txt])
    eh = open(ent_html, encoding="utf-8").read() if os.path.exists(ent_html) else ""
    et = open(ent_txt, encoding="utf-8").read() if os.path.exists(ent_txt) else ""
    check("HTML normalises stray entities in prose (no double-escaping like &amp;mdash; / &amp;lt;)",
          "&amp;mdash;" not in eh and "&amp;lt;" not in eh and "&amp;amp;" not in eh
          # the full injected phrases, rendered: `&mdash;` -> the em-dash char, `&amp;` -> a single `&amp;`,
          # `&lt;..&gt;` -> a single `&lt;..&gt;`. These exact substrings can't come from a template default.
          and "Tooling <code>a &amp; b</code> — see &lt;project&gt; notes." in eh
          and "Range &lt;1.0.0&gt; &amp; a — b." in eh,   # the injected RAISE rationale (esc path)
          "stray HTML entities in prose were double-escaped (or not normalised) in the HTML output")
    check("TXT decodes HTML entities in prose (no raw &amp;/&mdash;/&lt; in the summary)",
          "Tooling a & b — see <project> notes." in et
          and "&amp;" not in et and "&mdash;" not in et and "&lt;" not in et,
          "entities were not decoded in the .txt output")

    # 4. txt-only mode (no template needed)
    out_txt_only = os.path.join(tmp, "only.txt")
    r = run_render(["--findings", FIXTURE, "--out-txt", out_txt_only])
    check("--out-txt without --out-html works", r.returncode == 0 and os.path.exists(out_txt_only))

    # 4b. cited code that *looks* like a template placeholder must not corrupt the
    #     render or trip the "unsubstituted placeholder" check.
    spiced = json.loads(json.dumps(data))
    spiced["findings"][0]["evidence"].append({
        "file": "docker-compose.yml", "line": 12,
        "snippet": "DATABASE_URL: {{DATABASE_URL}}, AGENT: {{AGENT_NAME}}",
    })
    spiced["raise_posture"]["categories"][0]["rationale"] += " (config uses {{SCORE}} interpolation)"
    sp_path = os.path.join(tmp, "spiced.json")
    sp_html = os.path.join(tmp, "spiced.html")
    json.dump(spiced, open(sp_path, "w"))
    r = run_render(["--findings", sp_path, "--template", TEMPLATE, "--out-html", sp_html,
                    "--out-txt", os.path.join(tmp, "spiced.txt")])
    sp_out = open(sp_html, encoding="utf-8").read() if os.path.exists(sp_html) else ""
    check("render survives {{placeholder-like}} text in cited evidence/rationale",
          r.returncode == 0, r.stderr.strip())
    check("cited braces are neutralised, not substituted, and not flagged as unfilled",
          "{{DATABASE_URL}}" not in sp_out          # no raw double braces survive...
          and "{{AGENT_NAME}}" not in sp_out        # ...for either the cited or the template forms
          and "{{SCORE}}" not in sp_out
          and "&#123;&#123;DATABASE_URL&#125;&#125;" in sp_out   # cited braces -> entities
          and "FinBot" in sp_out)                   # the real AGENT_NAME placeholder still resolved

    # 4c. multi-paragraph behavior summary with inline emphasis: <p>/<strong>/<em>
    #     survive in HTML; the TXT flattens them (paragraph break -> space, tags dropped).
    rich = json.loads(json.dumps(data))
    rich["behavior_summary"] = ("<p>First paragraph ends with a period.</p>"
                                "<p>Second paragraph has <strong>bold</strong> and <em>italic</em> and "
                                "<code>code()</code> spans.</p>")
    rich_path = os.path.join(tmp, "rich.json")
    rich_html = os.path.join(tmp, "rich.html")
    rich_txt = os.path.join(tmp, "rich.txt")
    json.dump(rich, open(rich_path, "w"))
    r = run_render(["--findings", rich_path, "--template", TEMPLATE,
                    "--out-html", rich_html, "--out-txt", rich_txt])
    rh = open(rich_html, encoding="utf-8").read() if os.path.exists(rich_html) else ""
    rt = open(rich_txt, encoding="utf-8").read() if os.path.exists(rich_txt) else ""
    check("render succeeds with <p>/<strong>/<em>/<code> in behavior_summary",
          r.returncode == 0, r.stderr.strip())
    check("HTML keeps <p>/<strong>/<em>/<code> in the behavior summary",
          "<p>First paragraph" in rh and "<strong>bold</strong>" in rh
          and "<em>italic</em>" in rh and "<code>code()</code>" in rh)
    check("TXT flattens paragraphs to a space and drops all tags",
          "period. Second paragraph" in rt        # </p><p> -> single space, no run-together
          and "<strong>" not in rt and "<p>" not in rt and "<code>" not in rt
          and "</p>" not in rt and "<em>" not in rt
          and "bold" in rt and "italic" in rt and "code() spans" in rt)  # content kept, tags gone

    # 4d. v2.0 structured evidence renders as `file:line — snippet`;
    #     multi-item recommended_actions renders as a <ul>; single-item stays inline.
    sched = json.loads(json.dumps(data))
    sched["findings"][0]["evidence"] = [
        {"file": "src/foo.py", "line": 42, "snippet": "needs validation"},
        {"file": "src/bar.py", "line": None, "snippet": "file-level note"},
    ]
    sched["findings"][0]["recommended_actions"] = [
        "First action with a <code>code</code> span.",
        "Second action.",
    ]
    sched_path = os.path.join(tmp, "sched.json")
    sched_html = os.path.join(tmp, "sched.html")
    json.dump(sched, open(sched_path, "w"))
    r = run_render(["--findings", sched_path, "--template", TEMPLATE,
                    "--out-html", sched_html, "--out-txt", os.path.join(tmp, "sched.txt")])
    sh = open(sched_html, encoding="utf-8").read() if os.path.exists(sched_html) else ""
    check("v2.0 evidence renders as `file:line — snippet` and `file — snippet`",
          r.returncode == 0
          and "src/foo.py:42 — needs validation" in sh
          and "src/bar.py — file-level note" in sh, r.stderr.strip())
    check("multi-item recommended_actions renders as a <ul> with inline <code> preserved",
          "<ul><li>" in sh and "<code>code</code>" in sh and "Second action." in sh)

    # 4e. The published JSON-Schema doc and the Python validator agree on enum values.
    sch_path = os.path.join(SKILL_DIR, "findings.schema.json")
    js = json.load(open(sch_path, encoding="utf-8"))
    finding_props = js["properties"]["findings"]["items"]["properties"]
    rules_props = js["properties"]["remit_coverage"]["properties"]["rules"]["items"]["properties"]
    cat_props = js["properties"]["raise_posture"]["properties"]["categories"]["items"]["properties"]
    log_props = js["properties"]["log_files"]["properties"]["rows"]["items"]["properties"]
    pairs = [
        (finding_props["severity"]["enum"],    schema.SEVERITIES,   "severity"),
        (finding_props["confidence"]["enum"],  schema.CONFIDENCES,  "confidence"),
        (finding_props["raise_category"]["enum"], schema.RAISE_KEYS, "raise_category"),
        (finding_props["tags"]["items"]["properties"]["kind"]["enum"], schema.TAG_KINDS, "tag.kind"),
        (rules_props["status"]["enum"],        schema.REMIT_STATUSES, "remit-rule status"),
        (cat_props["key"]["enum"],             schema.RAISE_KEYS,     "raise category key"),
        (log_props["status"]["enum"],          schema.LOG_STATUSES,   "log status"),
        (finding_props["escalation"]["enum"],  schema.ESCALATIONS,    "escalation"),
    ]
    disagreements = [name for (jenum, penum, name) in pairs if list(jenum) != list(penum)]
    check("findings.schema.json enums agree with the Python validator constants",
          not disagreements, f"diverged: {disagreements}")

    # 5. negative cases — each must exit non-zero with a useful message
    def negative(name, mutate):
        bad = json.loads(json.dumps(data))
        path = os.path.join(tmp, "bad.json")
        if mutate is None:                       # special: write a legacy bare list
            json.dump([{"id": "x"}], open(path, "w"))
        else:
            mutate(bad)
            json.dump(bad, open(path, "w"))
        r = run_render(["--findings", path, "--out-txt", os.path.join(tmp, "n.txt")])
        check(name, r.returncode != 0 and bool(r.stderr.strip()),
              f"rc={r.returncode} stderr={r.stderr.strip()!r}")

    negative("rejects a legacy bare-list findings file", None)
    negative("rejects a missing required field (behavior_summary)",
             lambda d: d.pop("behavior_summary"))
    negative("rejects a footer/severity count mismatch",
             lambda d: d["footer"]["severity_counts"].__setitem__("critical", 99))
    negative("rejects a bad severity enum",
             lambda d: d["findings"][0].__setitem__("severity", "Sorta Bad"))
    negative("rejects a remit anchor pointing at a nonexistent finding",
             lambda d: d["remit_coverage"]["rules"][0].__setitem__("finding_id", "PRAX-9999-99-99-999"))
    negative("rejects fewer than six RAISE categories",
             lambda d: d["raise_posture"]["categories"].pop())
    negative("rejects a weighted_overall that doesn't match the category sum",
             lambda d: d["raise_posture"].__setitem__("weighted_overall", 4.99))

    # 6. committed regression baselines under tests/baselines/. The canonical
    #    JSON is the source of truth; the committed HTML/TXT are derived. For the
    #    post-relicense baselines (rendered with the current template) this asserts
    #    they re-render byte-for-byte from their JSON — the regression net that
    #    would have caught a renderer change silently desyncing a committed report.
    #    Pre-relicense baselines (and the schema-1.0 v0.2 set) keep the old report
    #    header by design — see tests/baselines/README.md → "Note on the relicense";
    #    those are validated as far as the current schema/template allow and the
    #    byte-compare is skipped. From praxa_version 0.6.0 on, the baseline must
    #    also quote its remit doc verbatim (tests/remits/<slug>.md): every rule_text
    #    and every `/`-separated policy_rule_text segment must be a substring.
    baselines_root = os.path.join(REPO_ROOT, "tests", "baselines")
    baseline_jsons = sorted(glob.glob(os.path.join(baselines_root, "*", "*", "*-findings-*.json")))
    check("found committed regression baselines under tests/baselines/", len(baseline_jsons) > 0)
    for bj in baseline_jsons:
        rel = os.path.relpath(bj, REPO_ROOT)
        data = json.load(open(bj, encoding="utf-8"))
        sv = str(data.get("schema_version", ""))
        if not sv.startswith("2."):
            check(f"baseline {rel}: schema_version {sv!r} — frozen pre-2.0 artifact, schema/render checks skipped", True)
            continue
        try:
            schema.validate(data)
            check(f"baseline {rel}: validates against schema.py", True)
        except schema.SchemaError as e:
            check(f"baseline {rel}: validates against schema.py", False, str(e))
            continue
        bdir = os.path.dirname(bj)
        c_html = next(iter(glob.glob(os.path.join(bdir, "*-analysis-*.html"))), None)
        c_txt = next(iter(glob.glob(os.path.join(bdir, "*-analysis-*.txt"))), None)
        check(f"baseline {rel}: has a committed .html and .txt alongside it", bool(c_html and c_txt))
        if not (c_html and c_txt):
            continue
        r_html = os.path.join(tmp, "bl.html")
        r_txt = os.path.join(tmp, "bl.txt")
        r = run_render(["--findings", bj, "--template", TEMPLATE, "--out-html", r_html, "--out-txt", r_txt])
        check(f"baseline {rel}: render exits 0", r.returncode == 0, r.stderr.strip())
        post_relicense = b"github.com/Exabeam/deckard" in open(c_html, "rb").read()
        if post_relicense and r.returncode == 0:
            check(f"baseline {rel}: HTML re-renders byte-identical from its JSON",
                  open(c_html, "rb").read() == open(r_html, "rb").read(),
                  "committed HTML differs from a fresh render of the committed JSON")
            check(f"baseline {rel}: TXT re-renders byte-identical from its JSON",
                  open(c_txt, "rb").read() == open(r_txt, "rb").read(),
                  "committed TXT differs from a fresh render of the committed JSON")
        else:
            check(f"baseline {rel}: pre-relicense template — byte re-render comparison skipped", True)
        # remit-quote invariant (praxa_version >= 0.6.0)
        try:
            pv = tuple(int(x) for x in str(data.get("praxa_version", "0")).split("."))
        except ValueError:
            pv = (0,)
        slug = data.get("scan", {}).get("agent_slug") or os.path.basename(bdir)
        remit_path = os.path.join(REPO_ROOT, "tests", "remits", f"{slug}.md")
        if pv >= (0, 6, 0):
            if not os.path.isfile(remit_path):
                check(f"baseline {rel}: has a matching tests/remits/{slug}.md", False)
            else:
                remit = open(remit_path, encoding="utf-8").read()
                quoted = []
                for rule in data["remit_coverage"]["rules"]:
                    quoted.append(("rule_text", rule["rule_id"], rule["rule_text"]))
                for f in data["findings"]:
                    for seg in f.get("policy_rule_text", "").split(" / "):
                        if seg.strip():
                            quoted.append(("policy_rule_text", f["id"], seg.strip()))
                missing = [(kind, who, txt) for (kind, who, txt) in quoted if txt not in remit]
                check(f"baseline {rel}: every rule_text / policy_rule_text is quoted verbatim from tests/remits/{slug}.md",
                      not missing,
                      "; ".join(f"{kind} of {who}: {txt[:60]!r}" for kind, who, txt in missing[:3]))
        else:
            check(f"baseline {rel}: praxa_version < 0.6.0 — remit-quote check skipped", True)

    print(f"\n{_passed} passed, {_failed} failed")
    return 1 if _failed else 0


if __name__ == "__main__":
    sys.exit(main())
